version: '2'
services:

  calvin-www:
    image: calvin
    build:
      context: ./
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    volumes:
      - ./dockerScripts:/temp/scripts
    ports:
      - 3000:3000
    depends_on:
      - calvin-cassandra
      - calvin-zookeeper
      - calvin-kafka
    entrypoint:
      -  /temp/scripts/wait-for-service.sh
      - '0.0.0.0'
      - '9042'
      - 'npm start'

  calvin-countermgr:
    image: counter
    build:
      context: ./
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    volumes:
      - ./dockerScripts:/temp/scripts
    depends_on:
      - calvin-cassandra
      - calvin-zookeeper
      - calvin-kafka
    entrypoint:
      -  /temp/scripts/wait-for-service.sh
      - '0.0.0.0'
      - '9042'
      - 'npm run svc.counter'

  calvin-memberlookup:
    image: member
    build:
      context: ./
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    volumes:
      - ./dockerScripts:/temp/scripts
    depends_on:
      - calvin-cassandra
      - calvin-zookeeper
      - calvin-kafka
    entrypoint:
      -  /temp/scripts/wait-for-service.sh
      - '0.0.0.0'
      - '9042'
      - 'npm run svc.member'

  calvin-toollookup:
    image: tool
    build:
      context: ./
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    volumes:
      - ./dockerScripts:/temp/scripts
    depends_on:
      - calvin-cassandra
      - calvin-zookeeper
      - calvin-kafka
    entrypoint:
      -  /temp/scripts/wait-for-service.sh
      - '0.0.0.0'
      - '9042'
      - 'npm run svc.tool'

  calvin-toolsink:
    image: toolsink
    build:
      context: ./
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    volumes:
      - ./dockerScripts:/temp/scripts
    depends_on:
      - calvin-cassandra
      - calvin-zookeeper
      - calvin-kafka
    entrypoint:
      -  /temp/scripts/wait-for-service.sh
      - '0.0.0.0'
      - '9042'
      - 'npm run svc.toolsink'

  calvin-cassandra:
    image: cassandra:latest
    network_mode: host
    restart: always
    expose:
      - 9042
    volumes:
      - /database:/var/lib/cassandra

  calvin-zookeeper:
    image: wurstmeister/zookeeper
    network_mode: host
    restart: always
    expose:
      - 2181

  calvin-kafka:
    image: wurstmeister/kafka
    network_mode: host
    restart: always
    expose:
      - 9092
    depends_on:
      - calvin-zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 0.0.0.0
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "CommunityLifecycleEvents:1:1,ToolEvents:1:1,CommunityActivityEvents:1:1"
      KAFKA_ZOOKEEPER_CONNECT: 0.0.0.0:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
